## Sangam 2019 Hackathon

In [1]:
import pandas as pd
import numpy as np

In [68]:
train_data = pd.read_csv("Train.csv", na_values=("NA", "", " "))
test_data = pd.read_csv("Test.csv", na_values=("NA", "", " "))

In [69]:
train_data.head()

date_time is_holiday  air_pollution_index  humidity  wind_speed  \
0  2012-10-02 09:00:00       None                  121        89           2   
1  2012-10-02 10:00:00       None                  178        67           3   
2  2012-10-02 11:00:00       None                  113        66           3   
3  2012-10-02 12:00:00       None                   20        66           3   
4  2012-10-02 13:00:00       None                  281        65           3   

   wind_direction  visibility_in_miles  dew_point  temperature  rain_p_h  \
0             329                    1          1       288.28       0.0   
1             330                    1          1       289.36       0.0   
2             329                    2          2       289.58       0.0   
3             329                    5          5       290.13       0.0   
4             329                    7          7       291.14       0.0   

   snow_p_h  clouds_all weather_type weather_description  traffic_volume  
0       0.0          40       Clouds    scattered clouds            5545  
1       0.0          75       Clouds       broken clouds            4516  
2       0.0          90       Clouds     overcast clouds            4767  
3       0.0          90       Clouds     overcast clouds            5026  
4       0.0          75       Clouds       broken clouds            4918

In [3]:
print(train_data.shape)
print(test_data.shape)

(33750, 15)
(14454, 14)


In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33750 entries, 0 to 33749
Data columns (total 15 columns):
date_time              33750 non-null object
is_holiday             33750 non-null object
air_pollution_index    33750 non-null int64
humidity               33750 non-null int64
wind_speed             33750 non-null int64
wind_direction         33750 non-null int64
visibility_in_miles    33750 non-null int64
dew_point              33750 non-null int64
temperature            33750 non-null float64
rain_p_h               33750 non-null float64
snow_p_h               33750 non-null float64
clouds_all             33750 non-null int64
weather_type           33750 non-null object
weather_description    33750 non-null object
traffic_volume         33750 non-null int64
dtypes: float64(3), int64(8), object(4)
memory usage: 3.9+ MB


In [5]:
train_data["date_time"] = pd.to_datetime(train_data["date_time"], format = "%Y%m%d %H:%M:%S")
train_data["date_time"] = train_data["date_time"].dt.day_name()

In [6]:
test_data["date_time"] = pd.to_datetime(test_data["date_time"], format = "%Y%m%d %H:%M:%S")
test_data["date_time"] = test_data["date_time"].dt.day_name()

In [7]:
train_data["date_time"] = train_data["date_time"].astype("category")
train_data["is_holiday"] = train_data["is_holiday"].astype("category")
train_data["weather_type"] = train_data["weather_type"].astype("category")
train_data["weather_description"] = train_data["weather_description"].astype("category")

In [8]:
test_data["date_time"] = test_data["date_time"].astype("category")
test_data["is_holiday"] = test_data["is_holiday"].astype("category")
test_data["weather_type"] = test_data["weather_type"].astype("category")
test_data["weather_description"] = test_data["weather_description"].astype("category")

In [9]:
print(train_data.head())
print(test_data.head())

  date_time is_holiday  air_pollution_index  humidity  wind_speed  \
0   Tuesday       None                  121        89           2   
1   Tuesday       None                  178        67           3   
2   Tuesday       None                  113        66           3   
3   Tuesday       None                   20        66           3   
4   Tuesday       None                  281        65           3   

   wind_direction  visibility_in_miles  dew_point  temperature  rain_p_h  \
0             329                    1          1       288.28       0.0   
1             330                    1          1       289.36       0.0   
2             329                    2          2       289.58       0.0   
3             329                    5          5       290.13       0.0   
4             329                    7          7       291.14       0.0   

   snow_p_h  clouds_all weather_type weather_description  traffic_volume  
0       0.0          40       Clouds    scattered clo

In [10]:
train_data.isnull().sum()

date_time              0
is_holiday             0
air_pollution_index    0
humidity               0
wind_speed             0
wind_direction         0
visibility_in_miles    0
dew_point              0
temperature            0
rain_p_h               0
snow_p_h               0
clouds_all             0
weather_type           0
weather_description    0
traffic_volume         0
dtype: int64

In [11]:
test_data.isnull().sum()

date_time              0
is_holiday             0
air_pollution_index    0
humidity               0
wind_speed             0
wind_direction         0
visibility_in_miles    0
dew_point              0
temperature            0
rain_p_h               0
snow_p_h               0
clouds_all             0
weather_type           0
weather_description    0
dtype: int64

In [12]:
## Splitting numerical and categorical variables
train_data_num = train_data.iloc[:, 2:12]
test_data_num = test_data.iloc[:, 2:12]

In [13]:
train_data_num.head()

air_pollution_index  humidity  wind_speed  wind_direction  \
0                  121        89           2             329   
1                  178        67           3             330   
2                  113        66           3             329   
3                   20        66           3             329   
4                  281        65           3             329   

   visibility_in_miles  dew_point  temperature  rain_p_h  snow_p_h  clouds_all  
0                    1          1       288.28       0.0       0.0          40  
1                    1          1       289.36       0.0       0.0          75  
2                    2          2       289.58       0.0       0.0          90  
3                    5          5       290.13       0.0       0.0          90  
4                    7          7       291.14       0.0       0.0          75

In [16]:
## Encoding categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
cat_var = ["date_time", "is_holiday", "weather_type", "weather_description"]
train_data_cat1 = pd.DataFrame()
test_data_cat1 = pd.DataFrame()
for col in cat_var:
    train_data_cat1[col] = le.fit_transform(train_data[col])
    test_data_cat1[col] = le.transform(test_data[col])

In [18]:
print(train_data.shape, train_data_cat1.shape)
print(test_data.shape, test_data_cat1.shape)

(33750, 15) (33750, 4)
(14454, 14) (14454, 4)


In [19]:
# train_data[["date_time", "is_holiday", "weather_type", "weather_description"]].head()
for i in ["date_time", "is_holiday", "weather_type", "weather_description"]:
    print(np.unique(train_data[i]),"\n", np.unique(train_data_cat1[i]))

['Friday' 'Monday' 'Saturday' 'Sunday' 'Thursday' 'Tuesday' 'Wednesday'] 
 [0 1 2 3 4 5 6]
['Christmas Day' 'Columbus Day' 'Independence Day' 'Labor Day'
 'Martin Luther King Jr Day' 'Memorial Day' 'New Years Day' 'None'
 'State Fair' 'Thanksgiving Day' 'Veterans Day' 'Washingtons Birthday'] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
['Clear' 'Clouds' 'Drizzle' 'Fog' 'Haze' 'Mist' 'Rain' 'Smoke' 'Snow'
 'Squall' 'Thunderstorm'] 
 [ 0  1  2  3  4  5  6  7  8  9 10]
['SQUALLS' 'Sky is Clear' 'broken clouds' 'drizzle' 'few clouds' 'fog'
 'freezing rain' 'haze' 'heavy intensity drizzle' 'heavy intensity rain'
 'heavy snow' 'light intensity drizzle' 'light intensity shower rain'
 'light rain' 'light rain and snow' 'light shower snow' 'light snow'
 'mist' 'moderate rain' 'overcast clouds' 'proximity shower rain'
 'proximity thunderstorm' 'proximity thunderstorm with drizzle'
 'proximity thunderstorm with rain' 'scattered clouds' 'shower drizzle'
 'shower snow' 'sky is clear' 'sleet' 'smoke' 'sn

In [20]:
for i in ["date_time", "is_holiday", "weather_type", "weather_description"]:
    print(np.unique(test_data[i]),"\n", np.unique(test_data_cat1[i]))

['Friday' 'Monday' 'Saturday' 'Sunday' 'Thursday' 'Tuesday' 'Wednesday'] 
 [0 1 2 3 4 5 6]
['Christmas Day' 'Columbus Day' 'Independence Day' 'Labor Day'
 'Martin Luther King Jr Day' 'Memorial Day' 'New Years Day' 'None'
 'State Fair' 'Thanksgiving Day' 'Veterans Day' 'Washingtons Birthday'] 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
['Clear' 'Clouds' 'Drizzle' 'Fog' 'Haze' 'Mist' 'Rain' 'Smoke' 'Snow'
 'Thunderstorm'] 
 [ 0  1  2  3  4  5  6  7  8 10]
['Sky is Clear' 'broken clouds' 'drizzle' 'few clouds' 'fog' 'haze'
 'heavy intensity drizzle' 'heavy intensity rain' 'heavy snow'
 'light intensity drizzle' 'light intensity shower rain' 'light rain'
 'light shower snow' 'light snow' 'mist' 'moderate rain' 'overcast clouds'
 'proximity shower rain' 'proximity thunderstorm'
 'proximity thunderstorm with drizzle' 'proximity thunderstorm with rain'
 'scattered clouds' 'shower drizzle' 'sky is clear' 'sleet' 'smoke' 'snow'
 'thunderstorm' 'thunderstorm with heavy rain'
 'thunderstorm with ligh

In [21]:
train = pd.concat([train_data_num, train_data_cat1], axis = 1)
test = pd.concat([test_data_num, test_data_cat1], axis = 1)

In [27]:
train.head()

air_pollution_index  humidity  wind_speed  wind_direction  \
0                  121        89           2             329   
1                  178        67           3             330   
2                  113        66           3             329   
3                   20        66           3             329   
4                  281        65           3             329   

   visibility_in_miles  dew_point  temperature  rain_p_h  snow_p_h  \
0                    1          1       288.28       0.0       0.0   
1                    1          1       289.36       0.0       0.0   
2                    2          2       289.58       0.0       0.0   
3                    5          5       290.13       0.0       0.0   
4                    7          7       291.14       0.0       0.0   

   clouds_all  date_time  is_holiday  weather_type  weather_description  
0          40          5           7             1                   24  
1          75          5           7             1                    2  
2          90          5           7             1                   19  
3          90          5           7             1                   19  
4          75          5           7             1                    2

In [32]:
test.shape

(14454, 14)

In [33]:
X = train
y = train_data["traffic_volume"].values

In [34]:
print(X.shape)
print(y.shape)

(33750, 14)
(33750,)


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [36]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [37]:
## Predicting validation set result
y_pred = regression.predict(X_val)
print(y_pred)
print(y_val)

[2679.83833689 2871.27372337 3793.82755534 ... 2875.35541728 2776.40273069
 3583.05143772]
[2789 4814 3238 ... 5739 3745 5597]


In [39]:
## Building the optimal model using backward elimination
import statsmodels.formula.api as sm
X = np.append(arr= np.ones((33750, 1)).astype(int), values= X, axis = 1)
X_opt = X[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     73.99
Date:                Thu, 01 Aug 2019   Prob (F-statistic):          1.91e-194
Time:                        15:20:47   Log-Likelihood:            -3.0380e+05
No. Observations:               33750   AIC:                         6.076e+05
Df Residuals:                   33736   BIC:                         6.077e+05
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4180.8843    574.157     -7.282      0.000   -5306.252   -3055.516
x1            -0.0900      0.128     -0.704      0.481      -0.340       0.160
x2             2.0131      0.642      3.135      0.002       0.754       3.272
x3            22.1597      5.369      4.127      0.000      11.636      32.684
x4             0.2907      0.109      2.660      0.008       0.077       0.505
x5             0.6161      2.080      0.296      0.767      -3.461       4.693
x6             0.6161      2.080      0.296      0.767      -3.461       4.693
x7            19.8713      0.809     24.568      0.000      18.286      21.457
x8             0.1998      0.200      1.000      0.317      -0.192       0.591
x9           946.6923   1097.146      0.863      0.388   -1203.752    3097.137
x10            4.4253      0.336     13.182      0.000       3.767       5.083
x11           35.0929      5.337      6.575      0.000      24.631      45.555
x12          216.2700     74.524      2.902      0.004      70.201     362.339
x13          -58.9877      4.565    -12.921      0.000     -67.936     -50.040
x14           -6.6841      1.235     -5.410      0.000      -9.106      -4.263
==============================================================================
Omnibus:                    45033.902   Durbin-Watson:                   0.201
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2180.530
Skew:                          -0.060   Prob(JB):                         0.00
Kurtosis:                       1.761   Cond. No.                     4.70e+18
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.36e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [48]:
X_test = np.append(arr= np.ones((14454, 1)).astype(int), values= test, axis = 1)

In [40]:
X_opt = X[:, [0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     80.15
Date:                Thu, 01 Aug 2019   Prob (F-statistic):          2.18e-195
Time:                        15:21:01   Log-Likelihood:            -3.0380e+05
No. Observations:               33750   AIC:                         6.076e+05
Df Residuals:                   33737   BIC:                         6.077e+05
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4173.3011    573.578     -7.276      0.000   -5297.534   -3049.068
x1            -0.0898      0.128     -0.703      0.482      -0.340       0.160
x2             2.0140      0.642      3.136      0.002       0.755       3.273
x3            22.1529      5.369      4.126      0.000      11.629      32.677
x4             0.2908      0.109      2.660      0.008       0.077       0.505
x5            19.8713      0.809     24.569      0.000      18.286      21.457
x6             0.1993      0.200      0.998      0.318      -0.192       0.591
x7           947.1192   1097.131      0.863      0.388   -1203.294    3097.533
x8             4.4248      0.336     13.181      0.000       3.767       5.083
x9            35.0962      5.337      6.576      0.000      24.635      45.558
x10          216.0609     74.519      2.899      0.004      70.000     362.122
x11          -58.9825      4.565    -12.921      0.000     -67.930     -50.035
x12           -6.6860      1.235     -5.412      0.000      -9.107      -4.264
==============================================================================
Omnibus:                    45045.023   Durbin-Watson:                   0.201
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2180.592
Skew:                          -0.060   Prob(JB):                         0.00
Kurtosis:                       1.761   Cond. No.                     4.03e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.03e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [41]:
X_opt = X[:, [0, 2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     87.40
Date:                Thu, 01 Aug 2019   Prob (F-statistic):          2.91e-196
Time:                        15:21:02   Log-Likelihood:            -3.0380e+05
No. Observations:               33750   AIC:                         6.076e+05
Df Residuals:                   33738   BIC:                         6.077e+05
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4188.1044    573.188     -7.307      0.000   -5311.572   -3064.636
x1             2.0144      0.642      3.137      0.002       0.756       3.273
x2            22.1673      5.369      4.129      0.000      11.644      32.691
x3             0.2906      0.109      2.659      0.008       0.076       0.505
x4            19.8691      0.809     24.566      0.000      18.284      21.454
x5             0.1993      0.200      0.997      0.319      -0.192       0.591
x6           941.1222   1097.089      0.858      0.391   -1209.210    3091.455
x7             4.4268      0.336     13.187      0.000       3.769       5.085
x8            35.1341      5.337      6.583      0.000      24.673      45.595
x9           216.2260     74.518      2.902      0.004      70.167     362.285
x10          -58.9815      4.565    -12.920      0.000     -67.929     -50.034
x11           -6.6804      1.235     -5.407      0.000      -9.102      -4.259
==============================================================================
Omnibus:                    45064.361   Durbin-Watson:                   0.201
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2180.697
Skew:                          -0.060   Prob(JB):                         0.00
Kurtosis:                       1.761   Cond. No.                     3.69e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.69e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [42]:
X_opt = X[:, [0, 2, 3, 4, 7, 8, 10, 11, 12, 13, 14]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     96.06
Date:                Thu, 01 Aug 2019   Prob (F-statistic):          4.16e-197
Time:                        15:21:04   Log-Likelihood:            -3.0380e+05
No. Observations:               33750   AIC:                         6.076e+05
Df Residuals:                   33739   BIC:                         6.077e+05
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4186.0977    573.181     -7.303      0.000   -5309.552   -3062.644
x1             2.0227      0.642      3.150      0.002       0.764       3.281
x2            22.1433      5.369      4.124      0.000      11.620      32.667
x3             0.2907      0.109      2.659      0.008       0.076       0.505
x4            19.8575      0.809     24.555      0.000      18.272      21.443
x5             0.1992      0.200      0.997      0.319      -0.192       0.591
x6             4.4304      0.336     13.199      0.000       3.772       5.088
x7            35.1732      5.337      6.591      0.000      24.713      45.634
x8           216.2497     74.518      2.902      0.004      70.191     362.308
x9           -58.8564      4.563    -12.900      0.000     -67.799     -49.914
x10           -6.6648      1.235     -5.395      0.000      -9.086      -4.244
==============================================================================
Omnibus:                    45101.035   Durbin-Watson:                   0.201
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2180.984
Skew:                          -0.060   Prob(JB):                         0.00
Kurtosis:                       1.761   Cond. No.                     1.94e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.94e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [43]:
X_opt = X[:, [0, 2, 3, 4, 7, 10, 11, 12, 13, 14]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.028
Model:                            OLS   Adj. R-squared:                  0.027
Method:                 Least Squares   F-statistic:                     106.6
Date:                Thu, 01 Aug 2019   Prob (F-statistic):          6.41e-198
Time:                        15:21:05   Log-Likelihood:            -3.0380e+05
No. Observations:               33750   AIC:                         6.076e+05
Df Residuals:                   33740   BIC:                         6.077e+05
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -4189.0885    573.173     -7.309      0.000   -5312.527   -3065.650
x1             2.0145      0.642      3.138      0.002       0.756       3.273
x2            22.1373      5.369      4.123      0.000      11.614      32.661
x3             0.2910      0.109      2.662      0.008       0.077       0.505
x4            19.8685      0.809     24.571      0.000      18.284      21.453
x5             4.4321      0.336     13.204      0.000       3.774       5.090
x6            35.1427      5.337      6.585      0.000      24.682      45.603
x7           216.2685     74.518      2.902      0.004      70.210     362.327
x8           -58.8153      4.562    -12.891      0.000     -67.758     -49.873
x9            -6.6451      1.235     -5.380      0.000      -9.066      -4.224
==============================================================================
Omnibus:                    45137.591   Durbin-Watson:                   0.201
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2181.241
Skew:                          -0.060   Prob(JB):                         0.00
Kurtosis:                       1.760   Cond. No.                     1.94e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.94e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [50]:
X_test.shape

(14454, 15)

In [51]:
X_test = X_test[:, [0, 2, 3, 4, 7, 10, 11, 12, 13, 14]]

In [45]:
test.shape

(14454, 14)

In [73]:
predict = regressor_OLS.predict(X_test)
predict

array([3214.15322736, 3279.61362709, 3473.9724086 , ..., 3003.53808107,
       3618.64075418, 3662.88377619])

In [74]:
type(predict)

numpy.ndarray

In [75]:
predict = predict.astype('int32')

In [76]:
predict

array([3214, 3279, 3473, ..., 3003, 3618, 3662])

In [77]:
final = pd.DataFrame({"date_time":test_data['date_time'], 'traffic_volume':predict})

In [78]:
#final.to_csv("submission_1.csv", index=False)